version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - VITE_BACKEND_URL=http://localhost:${BACKEND_PORT:-8000}
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - QDRANT_HOST=${QDRANT_HOST:-qdrant}
      - QDRANT_PORT=${QDRANT_PORT:-6333}
    depends_on:
      - qdrant
    restart: always
    volumes:
      - ./backend:/app

  qdrant:
    image: qdrant/qdrant
    ports:
      - "${QDRANT_PORT:-6333}:6333"
    volumes:
      - ./database/qdrant_data:/qdrant/storage
    restart: always
